# Generated by Django 4.2.6 on 2023-10-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ediprof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('coverimg', models.ImageField(blank=True, null=True, upload_to='product_picture/')),
                ('profimg', models.ImageField(blank=True, null=True, upload_to='product_picture/')),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('scholnam', models.CharField(blank=True, max_length=50, null=True)),
                ('univarName', models.CharField(blank=True, max_length=50, null=True)),
                ('liveName', models.CharField(max_length=50)),
                ('fromName', models.CharField(max_length=50)),
            ],
        ),
    ]
