# Generated by Django 4.2.6 on 2023-10-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ediprof',
            name='fromName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ediprof',
            name='liveName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
